version: 0.0
os: linux
files:
  - source: files
    destination: /usr/local/bin
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 60
      runas: root